server: 
  port: 9090
datasource:
  school:
    url: jdbc:postgresql://localhost:5432/school
    username: dzf
    password: 123456
  game:
    url: jdbc:postgresql://localhost:5432/game
    username: dzf
    password: 123456
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/dzf
#    username: dzf
#    password: 123456
    # Keep the connection alive if idle for a long time (needed in production)
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: create
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
    # stripped before adding them to the entity manager)
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  velocity:
    #日期格式处理
    dateToolAttribute: dateTool